kind: Deployment
apiVersion: apps/v1
metadata:
  name: azure-cognitive-service-custom-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: azure-cognitive-service-custom-proxy
      app.kubernetes.io/name: azure-cognitive-service-custom-proxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: azure-cognitive-service-custom-proxy
        app.kubernetes.io/name: azure-cognitive-service-custom-proxy
    spec:
      volumes:
        - name: forms-recognizer-shared
          persistentVolumeClaim:
            claimName: {{ include "form-recognizer.fullname" . }}-shared
        - name: forms-recognizer-logs
          persistentVolumeClaim:
            claimName: forms-recognizer-logs
      containers:
        - name: azure-cognitive-service-custom-proxy
          ports:
            - containerPort: 5200
              protocol: TCP
          image: >-
            image-registry.openshift-image-registry.svc:5000/0198bb-tools/forms-recognizer-proxy:latest
