apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-aio.fullname" . }}-agent
  labels:
    app: jaeger
    {{- include "jaeger-aio.labels" . | nindent 4 }}
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: agent-sampler-manager
    port: 5778
    protocol: TCP
    targetPort: 5778
  clusterIP: None
  selector:
    {{- include "jaeger-aio.selectorLabels" . | nindent 4 }}
