apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-aio.fullname" . }}-collector
  labels:
    app: jaeger
    {{- include "jaeger-aio.labels" . | nindent 4 }}
spec:
  ports:
  - name: jaeger-collector-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    {{- include "jaeger-aio.selectorLabels" . | nindent 4 }}
  type: ClusterIP
