version: "2"

checks:
  method-lines:
    config:
      threshold: 40
  similar-code:
    enabled: false
  complex-logic:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10

plugins:
  tslint:
    enabled: true
  markdownlint:
    enabled: false
  csslint:
    enabled: true
  similar-code:
    enabled: false

exclude_patterns:
  # Backend File Specific Excludes
  - "src/backend/TrafficCourts/Test/"
  - "src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client.Test/"
  - "src/backend/TrafficCourts/TrafficCourts.Common.Test/"
  - "src/backend/TrafficCourts/TrafficCourts.Messaging.Test/"
  - "src/backend/TrafficCourts/TrafficCourts.Staff.Service.Test/"
  - "src/backend/TrafficCourts/TrafficCourts.Workflow.Service.IntegrationTests/"
  
  # Generated Files
  - "src/backend/TrafficCourts/TrafficCourts.Arc.Dispute.Client/ArcDisputeClient.generated.cs"
  - "src/backend/TrafficCourts/Common/OpenAPIs/Keycloak/v18_0/KeycloakAdminApiClient.cs"
  - "src/backend/TrafficCourts/Common/OpenAPIs/OracleDataAPI/v1_0/OracleDataApiClient.cs"

  # Frontend Pattern Excludes
  - "src/frontend/*/karma.conf.js"
  - "src/frontend/*/package.json"
  - "src/frontend/*/tsconfig.json"
  - "src/frontend/*/tslint.json"
  - "src/frontend/*/**/*.spec.*"
  - "src/frontend/*/**/*.model.*"
  - "src/frontend/*/**/*.module.*"
  - "src/frontend/*/**/*.routes.*"
  - "src/frontend/*/**/abstract*.*"
  - "src/frontend/*/tests/"
  - "src/frontend/*/shared/components/"
  - "src/frontend/*/src/tests/mocks/"
  - "src/frontend/*/src/*.spec.ts"
  - "src/frontend/*/src/*/*/*.spec.ts"
  - "src/frontend/*/src/*.component.ts"
  - "src/frontend/*/src/*/*/*.component.ts"
  - "src/frontend/**/mock-*.ts"
