version: "3.8"

services:
  #############################################################################################
  ###                                  KEYCLOAK                                             ###
  #############################################################################################
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:5002/auth
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 5002:8080

  # #############################################################################################
  # ###                                  KEYCLOAK CONFIG                                      ###
  # #############################################################################################
  keycloak-config:
    build:
      context: ./infrastructure/keycloak
      args:
        - KEYCLOAK_URL=http://keycloak:8080
    command: sh -c "dockerize -wait http://keycloak:8080 -timeout 300s /tmp/createuser.sh"
    depends_on: [keycloak]

networks:
  traffic-court-net:
    driver: "bridge"
