version: "3.8"

services:

# #############################################################################################
# ###                                 TrafficCourt FRONTEND                                 ###
# #############################################################################################
#   citizen-portal:
#     # stdin_open: true
#     container_name: citizen-portal
#     build:
#       context: ./src/frontend/citizen-portal
#       dockerfile: Dockerfile.legacy
#       args:
#         - SERVICE_NAME=citizen-portal
#     ports:
#       - 4200:4200
#     networks:
#       - traffic-court-net
#     # environment:

#############################################################################################
###                                 TrafficCourt DEMO                                     ###
#############################################################################################  
  citizen-portal:
    container_name: citizen-portal
    build:
      context: ./src/frontend/citizen-portal
    command: "nginx -g 'daemon off;'"
      # environment:        
    restart: always
    ports:
      - "4201:4201"
    expose:
      - "4201"
    networks:
      - traffic-court-net

#############################################################################################
###                                  KEYCLOAK                                             ###
#############################################################################################  
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:8081/auth
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 8081:8080
    networks:
      - traffic-court-net

# #############################################################################################
# ###                                  KEYCLOAK CONFIG                                      ###
# #############################################################################################  
#   keycloak-config:
#     build:
#       context: ./infrastructure/keycloak
#       args:
#         - KEYCLOAK_URL=http://keycloak:8080
#     command: sh -c "dockerize -wait http://keycloak:8080 -timeout 300s -wait-retry-interval 10s /tmp/createuser.sh"
#     networks:
#       - traffic-court-net

#############################################################################################
###                                  SPLUNK                                               ###
#############################################################################################  
  splunk:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    ports:
      - 8000:8000
      - 8088:8088
    networks:
      - traffic-court-net
  
networks:
  traffic-court-net:
    driver: "bridge"    