/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DcfTemplateType = 'DcfTemplate' | 'HrDcfTemplate' | 'WrDcfTemplate';

export const DcfTemplateType = {
    DcfTemplate: 'DcfTemplate' as DcfTemplateType,
    HrDcfTemplate: 'HrDcfTemplate' as DcfTemplateType,
    WrDcfTemplate: 'WrDcfTemplate' as DcfTemplateType
};

