/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeRepresentedByLawyer = 'UNKNOWN' | 'Y' | 'N';

export const DisputeRepresentedByLawyer = {
    Unknown: 'UNKNOWN' as DisputeRepresentedByLawyer,
    Y: 'Y' as DisputeRepresentedByLawyer,
    N: 'N' as DisputeRepresentedByLawyer
};

