/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeInterpreterRequired = 'UNKNOWN' | 'Y' | 'N';

export const DisputeInterpreterRequired = {
    Unknown: 'UNKNOWN' as DisputeInterpreterRequired,
    Y: 'Y' as DisputeInterpreterRequired,
    N: 'N' as DisputeInterpreterRequired
};

