/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeAppearanceLessThan14DaysYn = 'UNKNOWN' | 'Y' | 'N';

export const DisputeAppearanceLessThan14DaysYn = {
    Unknown: 'UNKNOWN' as DisputeAppearanceLessThan14DaysYn,
    Y: 'Y' as DisputeAppearanceLessThan14DaysYn,
    N: 'N' as DisputeAppearanceLessThan14DaysYn
};

