/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JJDisputeHearingType } from './jJDisputeHearingType.model';
import { YesNo } from './yesNo.model';
import { JJDisputeStatus } from './jJDisputeStatus.model';


export interface DisputeCaseFileSummary { 
    id?: number;
    submittedTs?: string | null;
    jjDecisionDate?: string | null;
    signatoryName?: string | null;
    hearingType?: JJDisputeHearingType;
    ticketNumber?: string | null;
    violationDate?: string | null;
    violationDateCount?: number;
    toBeHeardAtCourthouseId?: number | null;
    toBeHeardAtCourthouseName?: string | null;
    disputantSurname?: string | null;
    disputantGivenName1?: string | null;
    disputantGivenName2?: string | null;
    disputantGivenName3?: string | null;
    status?: JJDisputeStatus;
    disputeStatusCd?: string | null;
    disputeStatusDescription?: string | null;
    statusDescription?: string | null;
    policeDetachment?: string | null;
    policeDetachmentId?: number | null;
    accidentYn?: YesNo;
    multipleOfficersYn?: YesNo;
    noticeOfHearingYn?: YesNo;
    electronicTicketYn?: YesNo;
    jjAssignedTo?: string | null;
    vtcAssignedTo?: string | null;
    vtcAssignedTs?: string | null;
    appearanceCourthouseId?: number | null;
    appearanceCourthouseName?: string | null;
    appearanceRoomCode?: string | null;
    appearanceTs?: string | null;
}
export namespace DisputeCaseFileSummary {
}


