/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeContactTypeCd = 'UNKNOWN' | 'INDIVIDUAL' | 'LAWYER' | 'OTHER';

export const DisputeContactTypeCd = {
    Unknown: 'UNKNOWN' as DisputeContactTypeCd,
    Individual: 'INDIVIDUAL' as DisputeContactTypeCd,
    Lawyer: 'LAWYER' as DisputeContactTypeCd,
    Other: 'OTHER' as DisputeContactTypeCd
};

