/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeCountPleaCode = 'UNKNOWN' | 'G' | 'N';

export const DisputeCountPleaCode = {
    Unknown: 'UNKNOWN' as DisputeCountPleaCode,
    G: 'G' as DisputeCountPleaCode,
    N: 'N' as DisputeCountPleaCode
};

