/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeListItemRequestCourtAppearanceYn = 'UNKNOWN' | 'Y' | 'N';

export const DisputeListItemRequestCourtAppearanceYn = {
    Unknown: 'UNKNOWN' as DisputeListItemRequestCourtAppearanceYn,
    Y: 'Y' as DisputeListItemRequestCourtAppearanceYn,
    N: 'N' as DisputeListItemRequestCourtAppearanceYn
};

