/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeUpdateRequestStatus2 = 'UNKNOWN' | 'ACCEPTED' | 'PENDING' | 'REJECTED';

export const DisputeUpdateRequestStatus2 = {
    Unknown: 'UNKNOWN' as DisputeUpdateRequestStatus2,
    Accepted: 'ACCEPTED' as DisputeUpdateRequestStatus2,
    Pending: 'PENDING' as DisputeUpdateRequestStatus2,
    Rejected: 'REJECTED' as DisputeUpdateRequestStatus2
};

