/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeCountRequestTimeToPay = 'UNKNOWN' | 'Y' | 'N';

export const DisputeCountRequestTimeToPay = {
    Unknown: 'UNKNOWN' as DisputeCountRequestTimeToPay,
    Y: 'Y' as DisputeCountRequestTimeToPay,
    N: 'N' as DisputeCountRequestTimeToPay
};

