/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeListItemDisputantDetectedOcrIssues = 'UNKNOWN' | 'Y' | 'N';

export const DisputeListItemDisputantDetectedOcrIssues = {
    Unknown: 'UNKNOWN' as DisputeListItemDisputantDetectedOcrIssues,
    Y: 'Y' as DisputeListItemDisputantDetectedOcrIssues,
    N: 'N' as DisputeListItemDisputantDetectedOcrIssues
};

