/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeStatus = 'UNKNOWN' | 'NEW' | 'VALIDATED' | 'PROCESSING' | 'REJECTED' | 'CANCELLED' | 'CONCLUDED';

export const DisputeStatus = {
    Unknown: 'UNKNOWN' as DisputeStatus,
    New: 'NEW' as DisputeStatus,
    Validated: 'VALIDATED' as DisputeStatus,
    Processing: 'PROCESSING' as DisputeStatus,
    Rejected: 'REJECTED' as DisputeStatus,
    Cancelled: 'CANCELLED' as DisputeStatus,
    Concluded: 'CONCLUDED' as DisputeStatus
};

