/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeCountRequestReduction = 'UNKNOWN' | 'Y' | 'N';

export const DisputeCountRequestReduction = {
    Unknown: 'UNKNOWN' as DisputeCountRequestReduction,
    Y: 'Y' as DisputeCountRequestReduction,
    N: 'N' as DisputeCountRequestReduction
};

