/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeListItemSystemDetectedOcrIssues = 'UNKNOWN' | 'Y' | 'N';

export const DisputeListItemSystemDetectedOcrIssues = {
    Unknown: 'UNKNOWN' as DisputeListItemSystemDetectedOcrIssues,
    Y: 'Y' as DisputeListItemSystemDetectedOcrIssues,
    N: 'N' as DisputeListItemSystemDetectedOcrIssues
};

