/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeSignatoryType = 'U' | 'D' | 'A';

export const DisputeSignatoryType = {
    U: 'U' as DisputeSignatoryType,
    D: 'D' as DisputeSignatoryType,
    A: 'A' as DisputeSignatoryType
};

