/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeCountRequestCourtAppearance = 'UNKNOWN' | 'Y' | 'N';

export const DisputeCountRequestCourtAppearance = {
    Unknown: 'UNKNOWN' as DisputeCountRequestCourtAppearance,
    Y: 'Y' as DisputeCountRequestCourtAppearance,
    N: 'N' as DisputeCountRequestCourtAppearance
};

