/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DisputeListItemStatus = 'UNKNOWN' | 'NEW' | 'VALIDATED' | 'PROCESSING' | 'REJECTED' | 'CANCELLED' | 'CONCLUDED';

export const DisputeListItemStatus = {
    Unknown: 'UNKNOWN' as DisputeListItemStatus,
    New: 'NEW' as DisputeListItemStatus,
    Validated: 'VALIDATED' as DisputeListItemStatus,
    Processing: 'PROCESSING' as DisputeListItemStatus,
    Rejected: 'REJECTED' as DisputeListItemStatus,
    Cancelled: 'CANCELLED' as DisputeListItemStatus,
    Concluded: 'CONCLUDED' as DisputeListItemStatus
};

