/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmailHistorySuccessfullySent = 'UNKNOWN' | 'Y' | 'N';

export const EmailHistorySuccessfullySent = {
    Unknown: 'UNKNOWN' as EmailHistorySuccessfullySent,
    Y: 'Y' as EmailHistorySuccessfullySent,
    N: 'N' as EmailHistorySuccessfullySent
};

