/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ExcludeStatus = 'UNKNOWN' | 'NEW' | 'VALIDATED' | 'PROCESSING' | 'REJECTED' | 'CANCELLED' | 'CONCLUDED';

export const ExcludeStatus = {
    Unknown: 'UNKNOWN' as ExcludeStatus,
    New: 'NEW' as ExcludeStatus,
    Validated: 'VALIDATED' as ExcludeStatus,
    Processing: 'PROCESSING' as ExcludeStatus,
    Rejected: 'REJECTED' as ExcludeStatus,
    Cancelled: 'CANCELLED' as ExcludeStatus,
    Concluded: 'CONCLUDED' as ExcludeStatus
};

