/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeSignatoryType = 'U' | 'D' | 'A';

export const JJDisputeSignatoryType = {
    U: 'U' as JJDisputeSignatoryType,
    D: 'D' as JJDisputeSignatoryType,
    A: 'A' as JJDisputeSignatoryType
};

