/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeCourtAppearanceRoPAppCd = 'UNKNOWN' | 'A' | 'P' | 'N';

export const JJDisputeCourtAppearanceRoPAppCd = {
    Unknown: 'UNKNOWN' as JJDisputeCourtAppearanceRoPAppCd,
    A: 'A' as JJDisputeCourtAppearanceRoPAppCd,
    P: 'P' as JJDisputeCourtAppearanceRoPAppCd,
    N: 'N' as JJDisputeCourtAppearanceRoPAppCd
};

