/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRequestTimeToPay = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRequestTimeToPay = {
    Unknown: 'UNKNOWN' as JJDisputedCountRequestTimeToPay,
    Y: 'Y' as JJDisputedCountRequestTimeToPay,
    N: 'N' as JJDisputedCountRequestTimeToPay
};

