/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeNoticeOfHearingYn = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputeNoticeOfHearingYn = {
    Unknown: 'UNKNOWN' as JJDisputeNoticeOfHearingYn,
    Y: 'Y' as JJDisputeNoticeOfHearingYn,
    N: 'N' as JJDisputeNoticeOfHearingYn
};

