/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPForWantOfProsecution = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRoPForWantOfProsecution = {
    Unknown: 'UNKNOWN' as JJDisputedCountRoPForWantOfProsecution,
    Y: 'Y' as JJDisputedCountRoPForWantOfProsecution,
    N: 'N' as JJDisputedCountRoPForWantOfProsecution
};

