/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPJailIntermittent = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRoPJailIntermittent = {
    Unknown: 'UNKNOWN' as JJDisputedCountRoPJailIntermittent,
    Y: 'Y' as JJDisputedCountRoPJailIntermittent,
    N: 'N' as JJDisputedCountRoPJailIntermittent
};

