/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeHearingType = 'UNKNOWN' | 'COURT_APPEARANCE' | 'WRITTEN_REASONS';

export const JJDisputeHearingType = {
    Unknown: 'UNKNOWN' as JJDisputeHearingType,
    CourtAppearance: 'COURT_APPEARANCE' as JJDisputeHearingType,
    WrittenReasons: 'WRITTEN_REASONS' as JJDisputeHearingType
};

