/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRequestReduction = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRequestReduction = {
    Unknown: 'UNKNOWN' as JJDisputedCountRequestReduction,
    Y: 'Y' as JJDisputedCountRequestReduction,
    N: 'N' as JJDisputedCountRequestReduction
};

