/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountPlea = 'UNKNOWN' | 'G' | 'N';

export const JJDisputedCountPlea = {
    Unknown: 'UNKNOWN' as JJDisputedCountPlea,
    G: 'G' as JJDisputedCountPlea,
    N: 'N' as JJDisputedCountPlea
};

