/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeCourtAppearanceRoPJjSeized = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputeCourtAppearanceRoPJjSeized = {
    Unknown: 'UNKNOWN' as JJDisputeCourtAppearanceRoPJjSeized,
    Y: 'Y' as JJDisputeCourtAppearanceRoPJjSeized,
    N: 'N' as JJDisputeCourtAppearanceRoPJjSeized
};

