/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeElectronicTicketYn = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputeElectronicTicketYn = {
    Unknown: 'UNKNOWN' as JJDisputeElectronicTicketYn,
    Y: 'Y' as JJDisputeElectronicTicketYn,
    N: 'N' as JJDisputeElectronicTicketYn
};

