/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeCourtAppearanceRoPCrown = 'UNKNOWN' | 'P' | 'N';

export const JJDisputeCourtAppearanceRoPCrown = {
    Unknown: 'UNKNOWN' as JJDisputeCourtAppearanceRoPCrown,
    P: 'P' as JJDisputeCourtAppearanceRoPCrown,
    N: 'N' as JJDisputeCourtAppearanceRoPCrown
};

