/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPWithdrawn = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRoPWithdrawn = {
    Unknown: 'UNKNOWN' as JJDisputedCountRoPWithdrawn,
    Y: 'Y' as JJDisputedCountRoPWithdrawn,
    N: 'N' as JJDisputedCountRoPWithdrawn
};

