/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeAppearInCourt = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputeAppearInCourt = {
    Unknown: 'UNKNOWN' as JJDisputeAppearInCourt,
    Y: 'Y' as JJDisputeAppearInCourt,
    N: 'N' as JJDisputeAppearInCourt
};

