/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountAppearInCourt = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountAppearInCourt = {
    Unknown: 'UNKNOWN' as JJDisputedCountAppearInCourt,
    Y: 'Y' as JJDisputedCountAppearInCourt,
    N: 'N' as JJDisputedCountAppearInCourt
};

