/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeAccidentYn = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputeAccidentYn = {
    Unknown: 'UNKNOWN' as JJDisputeAccidentYn,
    Y: 'Y' as JJDisputeAccidentYn,
    N: 'N' as JJDisputeAccidentYn
};

