/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputeCourtAppearanceRoPDattCd = 'UNKNOWN' | 'A' | 'C' | 'N';

export const JJDisputeCourtAppearanceRoPDattCd = {
    Unknown: 'UNKNOWN' as JJDisputeCourtAppearanceRoPDattCd,
    A: 'A' as JJDisputeCourtAppearanceRoPDattCd,
    C: 'C' as JJDisputeCourtAppearanceRoPDattCd,
    N: 'N' as JJDisputeCourtAppearanceRoPDattCd
};

