/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountRoPAbatement = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountRoPAbatement = {
    Unknown: 'UNKNOWN' as JJDisputedCountRoPAbatement,
    Y: 'Y' as JJDisputedCountRoPAbatement,
    N: 'N' as JJDisputedCountRoPAbatement
};

