/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JJDisputedCountIncludesSurcharge = 'UNKNOWN' | 'Y' | 'N';

export const JJDisputedCountIncludesSurcharge = {
    Unknown: 'UNKNOWN' as JJDisputedCountIncludesSurcharge,
    Y: 'Y' as JJDisputedCountIncludesSurcharge,
    N: 'N' as JJDisputedCountIncludesSurcharge
};

