/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DisputeCaseFileSummary } from './disputeCaseFileSummary.model';


export interface PagedDisputeCaseFileSummaryCollection { 
    items?: Array<DisputeCaseFileSummary> | null;
    pageNumber?: number;
    pageSize?: number;
    totalPages?: number;
    totalRows?: number;
}

