/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TicketImageDataJustinDocumentReportType = 'UNKNOWN' | 'NOTICE_OF_DISPUTE' | 'TICKET_IMAGE';

export const TicketImageDataJustinDocumentReportType = {
    Unknown: 'UNKNOWN' as TicketImageDataJustinDocumentReportType,
    NoticeOfDispute: 'NOTICE_OF_DISPUTE' as TicketImageDataJustinDocumentReportType,
    TicketImage: 'TICKET_IMAGE' as TicketImageDataJustinDocumentReportType
};

