/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketIsOwner = 'UNKNOWN' | 'Y' | 'N';

export const ViolationTicketIsOwner = {
    Unknown: 'UNKNOWN' as ViolationTicketIsOwner,
    Y: 'Y' as ViolationTicketIsOwner,
    N: 'N' as ViolationTicketIsOwner
};

