/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketCountIsAct = 'UNKNOWN' | 'Y' | 'N';

export const ViolationTicketCountIsAct = {
    Unknown: 'UNKNOWN' as ViolationTicketCountIsAct,
    Y: 'Y' as ViolationTicketCountIsAct,
    N: 'N' as ViolationTicketCountIsAct
};

