/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketCountIsRegulation = 'UNKNOWN' | 'Y' | 'N';

export const ViolationTicketCountIsRegulation = {
    Unknown: 'UNKNOWN' as ViolationTicketCountIsRegulation,
    Y: 'Y' as ViolationTicketCountIsRegulation,
    N: 'N' as ViolationTicketCountIsRegulation
};

