/**
 * VTC Staff API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ViolationTicketIsChangeOfAddress = 'UNKNOWN' | 'Y' | 'N';

export const ViolationTicketIsChangeOfAddress = {
    Unknown: 'UNKNOWN' as ViolationTicketIsChangeOfAddress,
    Y: 'Y' as ViolationTicketIsChangeOfAddress,
    N: 'N' as ViolationTicketIsChangeOfAddress
};

