/**
 * VTC Staff API
 * Violation Ticket Centre Staff API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type YesNo = 'Unknown' | 'Yes' | 'No';

export const YesNo = {
    Unknown: 'Unknown' as YesNo,
    Yes: 'Yes' as YesNo,
    No: 'No' as YesNo
};

