kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: clamav-build-bcgov
  namespace: 0198bb-tools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'clamav:bcgov'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: CLAMAV_NO_MILTERD
          value: 'true'
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/clamav'
      ref: master
    contextDir: /
  runPolicy: Serial
