{{- if and .Values.pdb.create (gt (.Values.replicaCount | toString | atoi) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "maintenance-site.fullname" . }}
  labels:
    {{- include "maintenance-site.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "maintenance-site.selectorLabels" . | nindent 6 }}
{{- end -}}
