apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ticket-search
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
        - name: url
          value: 'https://github.com/bcgov/jag-traffic-courts-online.git'
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: generate-id
      taskRef:
        name: t-generate-id
        kind: Task
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
    - name: docker-build-push
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/0198bb-tools/ticket-search
        - name: BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value:  ./Ticket.Search.Service/Dockerfile
        - name: CONTEXT
          value: src/backend/TrafficCourts
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: docker
      runAfter:
        - generate-id
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
      name: shared-data
