apiVersion: v1
kind: Service
metadata:
  name: {{ include "virusScan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "virusScan.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "virusScan.selectorLabels" . | nindent 4 }}
