# global values
global:
  namespace: 0198bb-test
  vault:
    role: 0198bb-nonprod
    path: test/
    
fullnameOverride: "virus-scan"

env:
  "CLAMAV__SERVER": "clamav.0198bb-test.svc.cluster.local"
