apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jaeger-aio.fullname" . }}
  labels:
    {{- include "jaeger-aio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "jaeger-aio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jaeger-aio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          {{- if .Values.storage.badger.enabled }}
          - name: SPAN_STORAGE_TYPE
            value: "badger"
          - name: BADGER_DIRECTORY_VALUE
            value: "/badger/data"
          - name: BADGER_DIRECTORY_KEY
            value: "/badger/key"
          - name: BADGER_EPHEMERAL
            value: {{ .Values.storage.badger.ephemeral | quote }}
          {{- end }}
          image: {{ template "jaeger.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: jaeger
          {{- if .Values.storage.memory.enabled }}
          args: ["--memory.max-traces={{ (int .Values.storage.memory.maxTraces) | default 50000 }}"]
          {{- end }}
          ports:
            - containerPort: 5775   # agent - accept zipkin.thrift over compact thrift protocol (deprecated)
              protocol: UDP
            - containerPort: 5778   # agent - config HTTP
              protocol: TCP
            - containerPort: 6831   # agent - accept jaeger.thrift over compact thrift protocol
              protocol: UDP
            - containerPort: 6832   # agent - accept jaeger.thrift over binary thrift protocol
              protocol: UDP
            - containerPort: 16686  # query - serve frontend
              protocol: TCP
            - containerPort: 4317   # collector - OTLP gRPC
              protocol: TCP
            - containerPort: 4318   # collector - OTLP HTTP
              protocol: TCP
            - containerPort: 9411   # collector - Zipkin
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: badger
              mountPath: /badger
      volumes:
        - name: badger
          persistentVolumeClaim:
            claimName: {{ include "jaeger-aio.fullname" . }}-badger
