apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: github-pat-token
  type: Opaque
  literals:
    - github-pat-token=
- name: github-webhook-secret
  type: Opaque
  literals:
    - github-webhook-secret=pWeqjPoqYapiYaUjo7kE2N5kqhzxEqdx
- name: image-registry-password
  type: Opaque
  literals:
    - image-registry-password=
- name: image-registry-username
  type: Opaque
  literals:
    - image-registry-username=
- name: ssh-key-path
  files:
    - .secrets/id_rsa
- name: docker-config-path
  files:
    - .secrets/.dockerconfigjson
  type: kubernetes.io/dockerconfigjson

