## Keycloak chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml

# image:
#  registry: image-registry.openshift-image-registry.svc:5000
#  repository: tools-namespace/keycloak

## Service configuration
##
service:
  type: ClusterIP

## Keycloak pods' SecurityContext
podSecurityContext:
  enabled: false

## Keycloak containers' Security Context
containerSecurityContext:
  runAsUser: 1000650000

## Metrics configuration
##
metrics:
  enabled: true

keycloakConfigCli:
  enabled: false

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
postgresql:
  enabled: false # we are going to use a shared postgresql instance

externalDatabase:
  host: "postgres"
  port: 5432
  user: keycloak
  database: keycloak
  existingSecret: "keycloak-postgres"
  existingSecretPasswordKey: "password"
