image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: 0198bb-tools/rabbitmq

containerSecurityContext:
  runAsUser: 1001280000

extraPlugins: ""

metrics:
  enabled: true

podSecurityContext:
  fsGroup: 1001280000

resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 512Mi

pdb:
  create: true
  minAvailable: 1

persistence:
  size: 1Gi

replicaCount: 3
