apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --provider=openshift --build=deploy-config
      --build-repo=https://github.com/bcgov/jag-traffic-courts-online.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: citizen-portal-demo
  name: citizen-portal-demo
spec:
  replicas: 1
  selector:
    io.kompose.service: citizen-portal-demo
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/traffic-court-net: "true"
        io.kompose.service: citizen-portal-demo
    spec:
      containers:
      - args:
        - nginx
        - -g
        - daemon off;
        env:
        - name: USE_KEYCLOAK
          value: "false"
        - name: USE_MOCK_SERVICES
          value: "true"
        image: ' '
        name: citizen-portal-demo
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - citizen-portal-demo
      from:
        kind: ImageStreamTag
        name: citizen-portal-demo:latest
    type: ImageChange
status: {}
