apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --provider=openshift --build=deploy-config
      --build-repo=https://github.com/bcgov/jag-traffic-courts-online.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: citizen-portal-demo
  name: citizen-portal-demo
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 8080
  selector:
    io.kompose.service: citizen-portal-demo
status:
  loadBalancer: {}
