apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --provider=openshift --build=deploy-config
      --build-repo=https://github.com/bcgov/jag-traffic-courts-online.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    io.kompose.service: keycloak
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/traffic-court-net: "true"
        io.kompose.service: keycloak
    spec:
      containers:
      - env:
        - name: DB_VENDOR
          value: H2
        - name: KEYCLOAK_FRONTEND_URL
        - name: KEYCLOAK_IMPORT
        - name: KEYCLOAK_PASSWORD
        - name: KEYCLOAK_USER
        image: ' '
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - keycloak
      from:
        kind: ImageStreamTag
        name: keycloak:latest
    type: ImageChange
status: {}
