apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert --provider=openshift --build=deploy-config
      --build-repo=https://github.com/bcgov/jag-traffic-courts-online.git
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: splunk
  name: splunk
spec:
  replicas: 1
  selector:
    io.kompose.service: splunk
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/traffic-court-net: "true"
        io.kompose.service: splunk
    spec:
      containers:
      - env:
        - name: SPLUNK_HEC_TOKEN
          value: h1a2r3s4h5
        - name: SPLUNK_PASSWORD
          value: Splunk@123
        - name: SPLUNK_START_ARGS
          value: --accept-license
        image: ' '
        name: splunk
        ports:
        - containerPort: 8000
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - splunk
      from:
        kind: ImageStreamTag
        name: splunk:latest
    type: ImageChange
status: {}
