
apiVersion: v1
kind: Service
metadata:
  name: common-object-management-service
  labels:
    app.kubernetes.io/part-of: common-object-management-service
    app.kubernetes.io/instance: common-object-management-service
    app.kubernetes.io/name: common-object-management-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: common-object-management-service
    app.kubernetes.io/name: common-object-management-service