apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: https
  namespace: 0198bb-tools
spec:
  podSelector: {}
  egress:
    - ports:
        - protocol: TCP
          port: 443
  policyTypes:
    - Egress