{{- if .Values.secrets.create }}
#
# not sure if will use a single secrets, or separate ones
# some services require a connection string instead of 
# separate values for things like redis, so use of secrets
# complicates that.
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traffic-court-online.fullname" . }}
  labels:
    {{- include "traffic-court-online.labels" . | nindent 4 }}
type: Opaque
stringData:

  # form-recognizer
  form-recognizer-endpoint:
  form-recognizer-api-key:
  
  # object-storage
  object-storage-access-key:
  object-storage-bucket-name:
  object-storage-endpoint:
  object-storage-secret-key:

  # rabbitmq
  rabbitmq-host:
  rabbitmq-username:
  rabbitmq-password:

  # redis
  redis-host:
  redis-port:
  redis-username:
  redis-password:
  
  # splunk
  splunk-hec-endpoint:
  splunk-hec-token: 
{{- end }}
