apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "form-recognizer.fullname" . }}-cleanup-logs
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: forms-recognizer-logs
              persistentVolumeClaim:
                claimName: {{ include "form-recognizer.fullname" . }}-logs
          containers:
            - name: {{ include "form-recognizer.fullname" . }}-cleanup-logs
              securityContext:
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              image: alpine:3.17.2
              args:
                - /bin/sh
                - '-c'
                - "LC_ALL=C find /logs -mtime +30 -delete;"
              volumeMounts:
                - name: forms-recognizer-logs
                  mountPath: /logs
          restartPolicy: OnFailure
