kind: Deployment
apiVersion: apps/v1
metadata:
  name: azure-cognitive-service-custom-supervised
spec:
  replicas: {{ .Values.supervised.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: azure-cognitive-service-custom-supervised
      app.kubernetes.io/name: azure-cognitive-service-custom-supervised
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: azure-cognitive-service-custom-supervised
        app.kubernetes.io/name: azure-cognitive-service-custom-supervised
    spec:
      volumes:
        - name: forms-recognizer-shared
          persistentVolumeClaim:
            claimName: forms-recognizer-shared
        - name: forms-recognizer-logs
          persistentVolumeClaim:
            claimName: forms-recognizer-logs
      containers:
        - name: azure-cognitive-service-custom-supervised
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          securityContext:
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: eula
              value: accept
            - name: Logging__Console__LogLevel__Default
              value: Information
            - name: Queue__RabbitMQ__HostName
              value: {{ .Values.rabbitmq.host | quote }}
            - name: Queue__RabbitMQ__Port
              value: {{ .Values.rabbitmq.port | quote }}
            - name: Queue__RabbitMQ__Username
              value: {{ .Values.rabbitmq.username | quote }}
            - name: Queue__RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secret.name }}
                  key: {{ .Values.rabbitmq.secret.passwordKey }}
            - name: SharedRootFolder
              value: /shared
            - name: Mounts__Shared
              value: /shared
            - name: Mounts__Output
              value: /logs
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.azure.apiKey.secret.name }}
                  key: {{ .Values.azure.apiKey.secret.key }}
            - name: billing
              value: {{ .Values.azure.billing.endpoint }}
            - name: CustomFormRecognizer__ContainerPhase
              value: All
            - name: CustomFormRecognizer__LayoutAnalyzeUri
              value: http://{{ include "form-recognizer.fullname" . }}-custom-layout:5000/formrecognizer/v2.1/layout/analyze
          volumeMounts:
            - name: forms-recognizer-shared
              mountPath: /shared
            - name: forms-recognizer-logs
              mountPath: /logs
          image: "{{ .Values.supervised.image.repository }}:{{ .Values.supervised.image.tag }}"
