apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "form-recognizer.fullname" . }}-cleanup-requests
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: forms-recognizer-shared
              persistentVolumeClaim:
                claimName: {{ include "form-recognizer.fullname" . }}-shared
          containers:
            - name: cleanup-requests
              securityContext:
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              image: alpine:3.17.2
              args:
                - /bin/sh
                - '-c'
                - "LC_ALL=C find /shared/formrecognizer/.__custom__.virtualdir/.__requests__.virtualdir/.__default__.virtualdir -mmin +60 -delete;"
              volumeMounts:
                - name: forms-recognizer-shared
                  mountPath: /shared
          restartPolicy: OnFailure
