kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "form-recognizer.fullname" . }}-custom-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-custom-api
      app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-custom-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "form-recognizer.fullname" . }}-custom-api
        app.kubernetes.io/name: {{ include "form-recognizer.fullname" . }}-custom-api
    spec:
      volumes:
        - name: forms-recognizer-shared
          persistentVolumeClaim:
            claimName: {{ include "form-recognizer.fullname" . }}-shared
        - name: forms-recognizer-logs
          persistentVolumeClaim:
            claimName: {{ include "form-recognizer.fullname" . }}-logs
      containers:
        - name: custom-api
          # securityContext:
          #   capabilities:
          #     drop: ["ALL"]
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: false
          #   seccompProfile:
          #     type: RuntimeDefault
          env:
            - name: eula
              value: accept
            - name: Logging__Console__LogLevel__Default
              value: Information
            - name: Queue__RabbitMQ__HostName
              value: rabbitmq
            - name: Queue__RabbitMQ__Port
              value: '5672'
            - name: SharedRootFolder
              value: /shared
            - name: Mounts__Shared
              value: /shared
            - name: Mounts__Output
              value: /logs
            - name: Queue__RabbitMQ__Username
              value: user
            - name: Queue__RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: apikey
              valueFrom:
                secretKeyRef:
                  name: {{ include "form-recognizer.fullname" . }}-secrets
                  key: FORMRECOGNIZER__APIKEY
            - name: billing
              valueFrom:
                secretKeyRef:
                  name: {{ include "form-recognizer.fullname" . }}-secrets
                  key: FORMRECOGNIZER__ENDPOINT
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: forms-recognizer-shared
              mountPath: /shared
            - name: forms-recognizer-logs
              mountPath: /logs
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
