kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: buildah
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '8.5-10'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel8/buildah:8.5-10'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '8.7-5'
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel8/buildah:8.7-5'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
