kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rabbitmq
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '3.9.13-debian-10-r55'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/rabbitmq:3.9.13-debian-10-r55'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.9.14-debian-10-r2'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/rabbitmq:3.9.14-debian-10-r2'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.9.26-debian-11-r0'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/rabbitmq:3.9.26-debian-11-r0'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.10.12-debian-11-r0'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/rabbitmq:3.10.12-debian-11-r0'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '3.11.9-debian-11-r2'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/rabbitmq:3.11.9-debian-11-r2'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
