kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: redis
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '6.2.6-debian-10-r158'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis:6.2.6-debian-10-r158'
        imagePullSecret: 'pipeline-docker-hub-pull'
      referencePolicy:
        type: Source
    - name: '6.2.7-debian-11-r62'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis:6.2.7-debian-11-r62'
        imagePullSecret: 'pipeline-docker-hub-pull'
      referencePolicy:
        type: Source
    - name: '7.0.5-debian-11-r23'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis:7.0.5-debian-11-r23'
        imagePullSecret: 'pipeline-docker-hub-pull'
      referencePolicy:
        type: Source
