# Default values for workflow-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param replicaCount Number of replicas
##
replicaCount: 1

image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: 0198bb-tools/workflow-service
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

## @param nameOverride String to partially override citizen-api.fullname template (will maintain the release name)
##
nameOverride: ""

## @param fullnameOverride String to fully override citizen-api.fullname template
##
fullnameOverride: ""

serviceAccount:
  # The name of the service account to use, defaults to "0198bb-vault"
  name: "0198bb-vault"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Autoscaling configuration
## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
## @param autoscaling.enabled Enable Horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
## @param autoscaling.targetMemoryUtilizationPercentage Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## @param rabbitmq
## Todo: move rabbitmq.password to secret
##
rabbitmq:
  host: rabbitmq
  port: "5672"
  username: guest
  password: guest

retry:
  times: 5
  interval: 2
  concurrencyLimit: 2

smtp:
  host: apps.smtp.gov.bc.ca
  port: 25

email:
  sender:
  allowed:

arc:
  host: arc-dispute-api
  port: 8080

oracle:
  host: oracle-data-api
  port: 8080

## @param jaeger
##
jaeger:
  enabled: false
  exporter:
    endpoint: http://jaeger-collector:14268/api/traces
    protocol: "http/thrift.binary"

vault:
  enabled: false
