apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${COMPONENT_NAME}
  description: RBAC permissions for RabbitMq cluster Service account for peer discovery and image pulling.

parameters:
  - name: COMPONENT_NAME
    description: The application name that each component is part of
    required: false
    value: rabbitmq-cluster
  
  - name: OC_SERVICEACCOUNT
    description: The name of the service account to be created for RabbitMq cluster
    required: false
    value: rabbitmq-discovery

  - name: OC_NAMESPACE
    description: The OpenShift namespace prefix
    required: true
    value: 0198bb

  - name: OC_ENV
    description: The OpenShift environment, ie dev, test or prod
    required: true
  
  

objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: ${OC_SERVICEACCOUNT}
    namespace: ${OC_NAMESPACE}-${OC_ENV}

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: endpoint-reader
    namespace: ${OC_NAMESPACE}-${OC_ENV}
  rules:
    - verbs:
        - get
      apiGroups:
        - ''
      resources:
        - endpoints

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: endpoint-reader
    namespace: ${OC_NAMESPACE}-${OC_ENV}
  subjects:
    - kind: ServiceAccount
      name: ${OC_SERVICEACCOUNT}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: endpoint-reader

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: rabbitmqsa:image-puller-${OC_NAMESPACE}-${OC_ENV}
    namespace: ${OC_NAMESPACE}-tools
  subjects:
  - kind: ServiceAccount
    name: ${OC_SERVICEACCOUNT}
    namespace: ${OC_NAMESPACE}-${OC_ENV}
  roleRef:
    kind: ClusterRole
    name: system:image-puller
    apiGroup: rbac.authorization.k8s.io
