apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ticket-search-service-environment-configmap.yaml
  - ticket-search-service-configuration-configmap.yaml
  - ticket-search-service-deployment.yaml
  - ticket-search-service.yaml
  - ticket-search-service-service-ca.yaml
