kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    description: Contains all the non-secret environment variables for the ticket-search-service deployment. Will be included by envFrom.
  name: ticket-search-service-environment
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: "https://0.0.0.0:8080"
  TICKETSEARCH__SEARCHTYPE: "Mock"
