apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-search-service
  labels:
    app: ticket-search-service
spec:
  selector:
    matchLabels:
      name: ticket-search-service
  replicas: 2
  template:
    metadata:
      labels:
        name: ticket-search-service  
    spec:
      containers:
        - name: ticket-search-service
          image: image-registry.openshift-image-registry.svc:5000/0198bb-tools/ticket-search-service
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:8080"
          - name: TICKETSEARCH__SEARCHTYPE
            value: "Mock"
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          livenessProbe:
            httpGet:
              path: /self
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /ready
                port: 8080
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
          resources:
            requests:
              cpu: 40m
              memory: 64Mi
            limits:
              cpu: 60m
              memory: 92Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

