version: "3.8"

services:
  #############################################################################################
  ###                           Azure Form Recognizer (3 containers)                        ###
  #############################################################################################
  
  citizen-api:
    environment:
      FORMRECOGNIZER__APIVERSION: ${FORMRECOGNIZER__APIVERSION:-2022-08-31}
      FORMRECOGNIZER__ENDPOINT: ${FORMRECOGNIZER__ENDPOINT:-http://azure-cognitive-service-proxy:5000}
      FORMRECOGNIZER__MODELID: ${FORMRECOGNIZER__MODELID:-ViolationTicket}

  form-rec-init:
    container_name: azure-cognitive-service-init
    build: 
      context: ./tools/form-recognizer/3.0/ 
      dockerfile: Dockerfile.initModels
    volumes:
      - type: bind
        source: ./tools/form-recognizer/3.0/shared
        target: /shared

  form-rec-proxy:
    image: nginx:alpine
    container_name: azure-cognitive-service-proxy
    depends_on:
      - form-rec-layout
      - form-rec-custom-template
      - form-rec-cron
    volumes:
      - ./tools/form-recognizer/3.0/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"

  form-rec-cron:
    container_name: azure-cognitive-service-custom-cron
    image: alpine:3.14
    entrypoint: >
      /bin/sh -c "
      LC_ALL=C find /shared/custom/.__default__.virtualdir -mmin +60 -delete;
      LC_ALL=C find /logs -mtime +30 -delete;
      exit 0;
      "
    volumes:
      - type: bind
        source: ./tools/form-recognizer/3.0/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/3.0/logs
        target: /logs

  form-rec-layout:
    container_name: azure-cognitive-service-layout
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-3.0:2022-08-31
    depends_on:
      - form-rec-init
    environment:
      eula: accept
      apikey: ${FORMRECOGNIZER__APIKEY}
      billing: ${FORMRECOGNIZER__BILLING_URL}
      Logging:Console:LogLevel:Default: Information
      SharedRootFolder: /shared
      Mounts:Shared: /shared
      Mounts:Output: /logs
    volumes:
      - type: bind
        source: ./tools/form-recognizer/3.0/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/3.0/logs
        target: /logs
    expose:
      - "5000"

  form-rec-custom-template:
    container_name: azure-cognitive-service-custom-template
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-template-3.0:2022-08-31
    restart: always
    depends_on:
      - form-rec-layout
    environment:
      AzureCognitiveServiceLayoutHost: http://azure-cognitive-service-layout:5000
      eula: accept
      apikey: ${FORMRECOGNIZER__APIKEY}
      billing: ${FORMRECOGNIZER__BILLING_URL}
      Logging:Console:LogLevel:Default: Information
      SharedRootFolder: /shared
      Mounts:Shared: /shared
      Mounts:Output: /logs
    volumes:
      - type: bind
        source: ./tools/form-recognizer/3.0/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/3.0/logs
        target: /logs
    expose:
      - "5000"
