# Use Jaeger tracing for services
version: "3.8"

services:
  #############################################################################################
  ###                           Jaeger                                                      ###
  #############################################################################################
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  citizen-api:
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      OTEL_EXPORTER_JAEGER_PROTOCOL: http/thrift.binary

  ticket-search:
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      OTEL_EXPORTER_JAEGER_PROTOCOL: http/thrift.binary
