# Use Splunk logging for services
version: "3.8"

services:

  #############################################################################################
  ###                           Splunk                                                      ###
  ###                                                                                       ###
  ### The default configuration is loaded from file ./.docker/splunk-dev-config.yaml        ###
  ###                                                                                       ###
  ### Web: http://localhost:8000   Username: admin, Password: password                      ###
  ### HEC: http://localhost:8088   Token: token                                             ###
  #############################################################################################
  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    ports:
      - 8000:8000
      - 8088:8088
    environment:
      SPLUNK_START_ARGS: --accept-license
      TZ: America/Vancouver
    volumes:
      - "./.docker/splunk-dev-config.yaml:/tmp/defaults/default.yml"

  arc-dispute-api:
    environment:
      Serilog__Using__0: Serilog.Sinks.Splunk
      Serilog__WriteTo__0__Name: EventCollector
      Serilog__WriteTo__0__Args:splunkHost: http://splunk:8088
      Serilog__WriteTo__0__Args:eventCollectorToken: token
    depends_on: [splunk]

  citizen-api:
    environment:
      Serilog__Using__0: Serilog.Sinks.Splunk
      Serilog__WriteTo__0__Name: EventCollector
      Serilog__WriteTo__0__Args:splunkHost: http://splunk:8088
      Serilog__WriteTo__0__Args:eventCollectorToken: token
    depends_on: [splunk]

  oracle-data-api:
    environment:
      SPLUNK_URL: ${SPLUNK_URL:-http://splunk:8088}
      SPLUNK_TOKEN: ${SPLUNK_HEC_TOKEN:-token}
    depends_on: [splunk]
  
  staff-api:
    environment:
      Serilog__Using__0: Serilog.Sinks.Splunk
      Serilog__WriteTo__0__Name: EventCollector
      Serilog__WriteTo__0__Args:splunkHost: http://splunk:8088
      Serilog__WriteTo__0__Args:eventCollectorToken: token
    depends_on: [splunk]

  workflow-service:
    environment:
      Serilog__Using__0: Serilog.Sinks.Splunk
      Serilog__WriteTo__0__Name: EventCollector
      Serilog__WriteTo__0__Args:splunkHost: http://splunk:8088
      Serilog__WriteTo__0__Args:eventCollectorToken: token
    depends_on: [splunk]

  