version: "3.8"

services:
  #############################################################################################
  ###                           Azure Form Recognizer (3 containers)                        ###
  #############################################################################################
  
  form-rec-nginx:
    image: nginx:alpine
    container_name: azure-cognitive-service-proxy
    volumes:
      - ./tools/form-recognizer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5200:5200"

  form-rec-layout:
    container_name: azure-cognitive-service-layout
    build:
      context: ../tools/form-recognizer
    depends_on:
      - rabbitmq
    environment:
      eula: accept
      apikey: ${FORMRECOGNIZER__APIKEY}
      billing: ${FORMRECOGNIZER__ENDPOINT}
      Queue:RabbitMQ:HostName: ${RABBITMQ__HOST}
      Queue:RabbitMQ:Port: ${RABBITMQ__PORT}
      Logging:Console:LogLevel:Default: Information
      SharedRootFolder: /shared
      Mounts:Shared: /shared
      Mounts:Output: /logs
    volumes:
      - type: bind
        source: ./tools/form-recognizer/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/logs
        target: /logs
    expose:
      - "5000"

  form-rec-custom-api:
    container_name: azure-cognitive-service-custom-api
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-api
    restart: always
    depends_on:
      - rabbitmq
    environment:
      eula: accept
      apikey: ${FORMRECOGNIZER__APIKEY}
      billing: ${FORMRECOGNIZER__ENDPOINT}
      Logging:Console:LogLevel:Default: Information
      Queue:RabbitMQ:HostName: ${RABBITMQ__HOST}
      Queue:RabbitMQ:Port: ${RABBITMQ__PORT}
      SharedRootFolder: /shared
      Mounts:Shared: /shared
      Mounts:Output: /logs
    volumes:
      - type: bind
        source: ./tools/form-recognizer/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/logs
        target: /logs
    expose:
      - "5000"

  form-rec-custom-supervised:
    container_name: azure-cognitive-service-custom-supervised
    image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/custom-supervised
    restart: always
    depends_on:
      - rabbitmq
    environment:
      eula: accept
      apikey: ${FORMRECOGNIZER__APIKEY}
      billing: ${FORMRECOGNIZER__ENDPOINT}
      CustomFormRecognizer:ContainerPhase: All
      CustomFormRecognizer:LayoutAnalyzeUri: http://azure-cognitive-service-layout:5000/formrecognizer/v2.1/layout/analyze
      Logging:Console:LogLevel:Default: Information
      Queue:RabbitMQ:HostName: ${RABBITMQ__HOST}
      Queue:RabbitMQ:Port: ${RABBITMQ__PORT}
      SharedRootFolder: /shared
      Mounts:Shared: /shared
      Mounts:Output: /logs
    volumes:
      - type: bind
        source: ./tools/form-recognizer/shared
        target: /shared
      - type: bind
        source: ./tools/form-recognizer/logs
        target: /logs