apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: traffic-court-pipelines

resources:
- ../../../components/tekton/base/pipelines
- ../../../components/tekton/base/tasks
- ../../../components/tekton/base/triggers
