apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-aio.fullname" . }}-query
  labels:
    app: jaeger
    {{- include "jaeger-aio.labels" . | nindent 4 }}
spec:
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
      protocol: TCP
      
  selector:
    {{- include "jaeger-aio.selectorLabels" . | nindent 4 }}
  type: ClusterIP
