version: "3.0"

services:

# #############################################################################################
# ###                                 Github  BACKEND                                  ###
# #############################################################################################
  network-tester:
    container_name: network-tester
    build:
      context: ./network-tester


#############################################################################################
###                                 Violation Ticket Generator                            ###
#############################################################################################
  ticket-gen:
    container_name: ticket-gen
    build:
      context: ./ticket-generator
    ports:
      - "8080:8080"

