version: "3.0"

services:

# #############################################################################################
# ###                                 Github  BACKEND                                  ###
# #############################################################################################
  networking-tools:
    container_name: network-tester
    build:
      context: ./network-tester
