version: "3.0"

services:

# #############################################################################################
# ###                                 Github  BACKEND                                  ###
# #############################################################################################
  network-tester:
    container_name: network-tester
    build:
      context: ./network-tester


#############################################################################################
###                                 Violation Ticket Generator                            ###
#############################################################################################
  ticket-gen:
    container_name: ticket-gen
    build:
      context: ./ticket-generator
    ports:
      - "8080:8080"

#############################################################################################
###                            H2 database to support OCR Metrics                         ###
#############################################################################################
  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - ./form-recognizer/metrics/data/db:/opt/h2-data
      
#############################################################################################
###                                 Keycloak User Initializer                             ###
#############################################################################################
  keycloak-user-init:
    container_name: keycloak-init
    environment:
      IDIR_API_CLIENT_ID: ${IDIR_API_CLIENT_ID:-id}
      IDIR_API_CLIENT_SECRET: ${IDIR_API_CLIENT_SECRET:-secret}
      IDIR_API_DEBUG: ${IDIR_API_DEBUG:-false}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-id}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-secret}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-realm}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:-localhost}
    build:
      context: ./keycloak-user-initializer
    ports:
      - "8081:8080"
