version: "3.8"

services:

  splunk:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_HEC_TOKEN=traffic
      - SPLUNK_PASSWORD
    ports:
      - 8000:8000
      - 8088:8088
