kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: virus-scan-api-build
  namespace: 0198bb-tools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'virus-scan-api:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        - name: ASPNETCORE_URLS
          value: 'http://*:8080'
      dockerfilePath: src/backend/bc-gov-virus-scan/BCGov.VirusScan.Api/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/jag-traffic-courts-online'
      ref: main
    contextDir: src/backend/bc-gov-virus-scan
  runPolicy: Serial
