openapi: 3.0.3
info:
  description: This is an Oracle REST Data Services (ORDS) service for the Traffic Court Online schema.
  title: Traffic Court Online
  version: 1.0.0
servers:
  - description: local
    url: 'https://ords-0198bb-dev.apps.silver.devops.gov.bc.ca/tcoords/tco/'
paths:
  /v1/ping:
    get:
      operationId: ping
      summary: Pings the server to test the connection
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResult'
      tags:
        - Health
  /v1/jjDispute:
    get:
      parameters:
        - name: ticketNumber
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JJDispute'
      tags:
        - JJDispute
  /v1/updateDispute:
    put:
      requestBody:
        description: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JJDispute'
        required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResult'
      tags:
        - JJDispute
  /v1/jjDisputeList:
    get:
      parameters:
        - name: justinRccId
          in: query
          schema:
            type: string
        - name: ticketNumber
          in: query
          schema:
            type: string
        - name: violationTicketId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JJDisputeListResponse'
      tags:
        - JJDispute
  /v1/disputeStatus:
    post:
      parameters:
        - name: disputeId
          in: query
          required: true
          description: ''
          schema:
            type: integer
            format: int64
        - name: courtAppearanceId
          in: query
          description: ''
          schema:
            type: integer
            format: int64
        - name: statusCd
          in: query
          required: true
          description: ''
          schema:
            type: string
            maxLength: 4
        - name: seizedYn
          in: query
          description: ''
          schema:
            type: string
            maxLength: 1
        - name: adjudicatorPartId
          in: query
          description: ''
          schema:
            type: string
            maxLength: 20
        - name: aattCd
          in: query
          description: 'Disputant presence code'
          schema:
            type: string
            maxLength: 3
        - name: dattCd
          in: query
          description: 'Defence counsel presence code'
          schema:
            type: string
            maxLength: 1
        - name: staffPartId
          in: query
          description: ''
          schema:
            type: string
            maxLength: 20
        - name: userId
          in: query
          required: true
          description: 'This is actually userName, not a user ID.'
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseResult'
      tags:
        - JJDispute
  /v1/processDisputeRemark:
    post:
      requestBody:
        description: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JJDisputeRemark'
        required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemarkResponseResult'
      tags:
        - JJDispute
components:
  schemas:
    AuditBase:
      type: object
      properties:
        entDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        entUserId:
          type: string
        updDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        updUserId:
          type: string
          format: nullable
    JJDispute:
      type: object
      properties:          
        addressLine1Txt:
          type: string
        addressLine2Txt:
          type: string
          format: nullable
        addressLine3Txt:       
          type: string 
          format: nullable
        addressCityTxt:
          type: string
          format: nullable
        addressProvinceTxt:
          type: string
          format: nullable
        addressCountryTxt:
          type: string
          format: nullable
        addressPostalCodeTxt:
          type: string
          format: nullable
        courtHearingTypeCd:  
          type: string 
        contactLawFirmNm:
          type: string
          format: nullable
        contactGiven1Nm:
          type: string
          format: nullable
        contactGiven2Nm:
          type: string
          format: nullable
        contactGiven3Nm:
          type: string
          format: nullable
        contactSurnameNm:
          type: string
          format: nullable
        contactTypeCd:
          type: string
        courtAgenId:
          type: string
        courtAppearances:
          type: array
          items:
            $ref: '#/components/schemas/JJCourtAppearance'
        detachmentLocationTxt:
          type: string
          format: nullable
        disputantBirthDt:
          type: string
          format: date  
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd\")"
        disputantDrvLicNumberTxt:
          type: string
          format: nullable
        disputantGiven1Nm:
          type: string
          format: nullable
        disputantGiven2Nm:
          type: string
          format: nullable
        disputantGiven3Nm:
          type: string
          format: nullable
        disputantSurnameTxt:
          type: string
          format: nullable
        disputeCounts:
          type: array
          items:
            $ref: '#/components/schemas/JJDisputeCount'
        disputeId:
          type: string
        disputeRemarks:
          type: array
          items:
            $ref: '#/components/schemas/JJDisputeRemark'
        disputeStatusTypeCd:
          type: string
        drvLicIssuedCtryId:
          type: string
          format: nullable
        drvLicIssuedProvSeqNo:
          type: string
          format: nullable
        emailAddressTxt:
          type: string
          format: nullable
        fineReductionReasonTxt:
          type: string
          format: nullable
        jjAssignedTo:
          type: string
          format: nullable
        jjDecisionDt:
          type: string
          format: date
        justinRccId:
          type: string
        icbcReceivedDt:
          type: string
          format: date  
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd\")"
        interpreterLanguageCd:
          type: string
          format: nullable
        issuedTs:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm'Z'\")"
        lawFirmNm:
          type: string
          format: nullable
        lawyerGiven1Nm:
          type: string
          format: nullable
        lawyerGiven2Nm:
          type: string
          format: nullable
        lawyerGiven3Nm:
          type: string
          format: nullable
        lawyerSurnameNm:
          type: string
          format: nullable
        noticeOfDisputeGuid:
          type: string
        occamDisputantGiven1Nm:
          type: string
          format: nullable
        occamDisputantGiven2Nm:
          type: string
          format: nullable
        occamDisputantGiven3Nm:
          type: string
          format: nullable
        occamDisputantSurnameNm:
          type: string
          format: nullable
        occamDisputeId:
          type: string
        occamViolationTicketUpldId:
          type: string
        offenceLocationTxt:
          type: string
          format: nullable
        submittedDt:
          type: string
          format: date  
        ticketNumberTxt:
          type: string
        timeToPayReasonTxt:
          type: string
          format: nullable
        violationDt:
          type: string
          format: date
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd\")"
        vtcAssignedTo:
          type: string
          format: nullable
        vtcAssignedDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        witnessNo:
          type: string
          format: nullable
      allOf:
        - $ref: '#/components/schemas/AuditBase'
    JJDisputeListResponse:
      type: object
      properties:
        jjDisputes:
          type: array
          items:
            $ref: '#/components/schemas/JJDispute'
    JJDisputeCount:
      type: object
      properties:
        abatementYn:
          type: string
        accEntDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        accEntUserId:
          type: string
        accUpdDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        accUpdUserId:
          type: string
        adjustedAmt:
          type: double
        appearanceChargeCountId:
          type: string
        commentsTxt:
          type: string
        countNo:
          type: string
        courtAppearanceId:
          type: string
        dismissedForWantProsecYn:
          type: string
        dismissedYn:
          type: string
        disputeCountId:
          type: string
        disputeId:
          type: string
        drivingProhibDurationTxt:
          type: string
        drivingProhibMvaSectionTxt:
          type: string
        findingResultCd:
          type: string
        fineDueDt:
          type: string
          format: date
        includesSurchargeYn:
          type: string
        jailDurationTxt:
          type: string
        jailIntermittentYn:
          type: string
        lesserChargeDescTxt:
          type: string
        otherTxt:
          type: string
        pleaCd:
          type: string
        probationConditionsTxt:
          type: string
        probationDurationTxt:
          type: string
        remarksTxt:
          type: string
        requestCourtAppearanceYn:
          type: string
        requestReductionYn:
          type: string
        requestTimeToPayYn:
          type: string
        revisedDueDt:
          type: string
          format: date
        statuteId:
          type: string
        stayOfProceedingsByTxt:
          type: string
        suspSntcProbationCondsTxt:
          type: string
        suspSntcProbationDurtnTxt:
          type: string
        ticketedAmt:
          type: double
        totalFineAmt:
          type: double
        violationDt:
          type: string
          format: date
        withdrawnYn:
          type: string
      allOf:
        - $ref: '#/components/schemas/AuditBase'
    JJCourtAppearance:
      type: object
      properties:
        appearanceDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        appearanceReasonTxt:
          type: string
        commentsTxt:
          type: string
        courtroomNumberTxt:
          type: string
        courtAppearanceId:
          type: string
        crownPresenceCd:
          type: string
        defenceCounselNameTxt:
          type: string
        defenceCounselPresenceCd:
          type: string
        disputeId:
          type: string
        disputantPresenceCd:
          type: string
        disputantNotPresentDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
        judgeOrJjNameTxt:
          type: string
        recordingClerkNameTxt:
          type: string
        seizedYn:
          type: string
      allOf:
        - $ref: '#/components/schemas/AuditBase'
    JJDisputeRemark:
      type: object
      properties:
        disputeRemarkId:
          type: string
        disputeId:
          type: string
        disputeRemarkTxt:
          type: string
        fullUserNameTxt:
          type: string
        remarksMadeDtm:
          type: string
          format: date-time
          x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonFormat(pattern=\"yyyy-MM-dd'T'HH:mm:ss'Z'\")"
      allOf:
        - $ref: '#/components/schemas/AuditBase'
    PingResult:
      type: object
      properties:
        status:
          type: string
        currentTimestamp:
          type: string
          format: date-time
    ResponseResult:
      type: object
      properties:
        status:
          type: string
        disputeId:
          type: string
          format: nullable
        exception:
          type: string
          format: nullable
    RemarkResponseResult:
      type: object
      properties:
        status:
          type: string
        disputeRemarkId:
          type: string
          format: nullable
        exception:
          type: string
          format: nullable
