kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: cassandra
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '4.1.4-debian-12-r5'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/cassandra:4.1.4-debian-12-r5'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '4.0.12-debian-12-r9'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bitnami/cassandra:4.0.12-debian-12-r9'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
