kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: common-object-management-service
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '0.4.2'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/bcgovimages/common-object-management-service:0.4.2'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
