kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dotnet-sdk
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '8.0'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/microsoft-docker-remote/dotnet/sdk:8.0'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '7.0'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/microsoft-docker-remote/dotnet/sdk:7.0'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dotnet-80-runtime
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/dotnet-80-runtime:latest'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: dotnet-70-runtime
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/dotnet-70-runtime:latest'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
