kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: form-recognizer-custom-template-3.0
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '2022-08-31'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/microsoft-docker-remote/azure-cognitive-services/form-recognizer/custom-template-3.0:2022-08-31'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
