kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: maven
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '3.8.6-jdk-11'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/docker-remote/maven:3.8.6-jdk-11'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
