kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nginx-120
  namespace: 0198bb-tools
  labels:
    usage: build-pipeline-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/nginx-120:latest'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1-127'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/nginx-120:1-127.1698060561'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1-92'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/nginx-120:1-92'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1-74'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/nginx-120:1-74'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1-54'
      from:
        kind: DockerImage
        name: 'artifacts.developer.gov.bc.ca/redhat-access-docker-remote/ubi8/nginx-120:1-54'
        imagePullSecret: 'artifacts-default-gpffbq'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
