kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: redis-exporter
  namespace: 0198bb-tools
  labels:
    usage: runtime-image
spec:
  lookupPolicy:
    local: true
  tags:
    - name: '1.55.0-debian-11-r0'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis-exporter:1.55.0-debian-11-r0'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1.54.0-debian-11-r25'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis-exporter:1.54.0-debian-11-r25'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1.50.0-debian-11-r13'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis-exporter:1.50.0-debian-11-r13'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1.46.0-debian-11-r7'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis-exporter:1.46.0-debian-11-r7'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
    - name: '1.36.0-debian-10-r5'
      from:
        kind: DockerImage
        name: 'docker.io/bitnami/redis-exporter:1.36.0-debian-10-r5'
        imagePullSecret: 'pipeline-docker-hub-pull'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
