name: Build Form Recognizer Layout Image and Push to Openshift Registry
on:
  push:
    branches: [main]
    paths:
      - 'tools/form-recognizer/3.0/**'
      - '.github/workflows/ci-acs-form-recognizer-init.yml'
jobs:
  build-acs-form-recognizer-init:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./tools/form-recognizer/3.0
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/acs-form-recognizer-init
        run: |
          git_sha=$(git rev-parse --short HEAD)
          docker build --tag ${IMAGE}:${git_sha} -f ${CONTEXT}/Dockerfile.initModels ${CONTEXT}
          docker push ${IMAGE}:${git_sha}
          docker tag ${IMAGE}:${git_sha} ${IMAGE}:latest
          docker push ${IMAGE}:latest
