name: Build Form Recognizer Proxy Image and Push to Openshift Registry
on:
  push:
    branches: [spike/azure-ocr]
    paths:
      - 'tools/form-recognizer/Dockerfile.proxy'
      - 'tools/form-recognizer/nginx.conf'
      - '.github/workflows/pr-azure-cognitive-service-proxy.yml'
jobs:
  build-azure-custom-proxy:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./tools/form-recognizer
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/forms-recognizer-proxy:latest
        run: |
          docker build --tag ${IMAGE} -f ${CONTEXT}/Dockerfile.proxy ${CONTEXT}
          docker push ${IMAGE}
