name: Citizen API

on:
  pull_request:
    paths:
      - 'src/backend/TrafficCourts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        working-directory: ./src/backend/TrafficCourts
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Build Citizen Api
        run: dotnet build --configuration Release /p:EmitCompilerGeneratedFiles=true
      - name: Run Tests
        run: dotnet test --configuration Release /p:EmitCompilerGeneratedFiles=true
