name: Ticket Search

on:
  pull_request:
    paths:
      - 'src/backend/TrafficCourts/Test/**'
      - 'src/backend/TrafficCourts/TrafficCourts.Ticket.Search.Service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.200
      - name: build ticket-search
        run: dotnet build TrafficCourts.Ticket.Search.Service/TrafficCourts.Ticket.Search.Service.csproj
        working-directory: ./src/backend/TrafficCourts
      - name: test ticket-search
        run: dotnet test Test/TrafficCourts.Test.csproj
        working-directory: ./src/backend/TrafficCourts
