name: Test-Build .NET API Image and Push to Openshift Registry
on:
  push:
    branches: [test]
  workflow_dispatch:
    branches: [test]
jobs:
  build-api:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to RedHat
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.REDHAT_REPO}}
          username: ${{secrets.REDHAT_REPO_USER}}
          password: ${{secrets.REDHAT_REPO_AUTH}}

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/backend
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/dispute-api:dev
          build-args:
            ASPNETCORE_ENVIRONMENT=Development
            SPLUNK_COLLECTOR_URL=${{secrets.SPLUNK_COLLECTOR_URL}}
            SPLUNK_TOKEN=${{secrets.SPLUNK_HEC_TOKEN}}
            OAUTH__OAUTHURL=${{secrets.OAUTH__OAUTHURL}}
            OAUTH__RESOURCEURL=${{secrets.OAUTH__RESOURCEURL}}
            OAUTH__CLIENTID=${{secrets.OAUTH__CLIENTID}}
            OAUTH__SECRET=${{secrets.OAUTH__SECRET}}
            RSI__BASEADDRESS=${{secrets.RSI__BASEADDRESS}}
            
  build-frontend:
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to RedHat
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.REDHAT_REPO}}
          username: ${{secrets.REDHAT_REPO_USER}}
          password: ${{secrets.REDHAT_REPO_AUTH}}

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/frontend/citizen-portal
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/citizen-portal:dev
          build-args:
            API_URL=${{secrets.API_URL}} 
            KEYCLOAK_URL=${{secrets.KEYCLOAK_URL}} 
            KEYCLOAK_REALM=${{secrets.KEYCLOAK_REALM}} 
            KEYCLOAK_CLIENT_ID=${{secrets.KEYCLOAK_CLIENT_ID}} 
            USE_MOCK_SERVICES=${{secrets.USE_MOCK_SERVICES}} 
            USE_KEYCLOAK=${{secrets.USE_KEYCLOAK}} 
